### ISSUE TITLE
Error on running exe

### ISSUE THREAD

**Issue by RidhwaanCodesStuff** [ahsan-a/Powermote#2]
App is programmed to the directory of @ahsan-a and will not work on other PC's.
![image](https://user-images.githubusercontent.com/64429064/97084988-6e426700-1612-11eb-924c-942c3d49d9b7.png)

**Comment by ahsan-a** [comment]
try running ```nets http add urlacl url=http://+:1337/ user="Everyone"``` and let me know what happens.

**Comment by RidhwaanCodesStuff** [comment]
![image](https://user-images.githubusercontent.com/64429064/97085390-1c4f1080-1615-11eb-9b3c-caab2b3325a4.png)

**Comment by RidhwaanCodesStuff** [comment]
didnt work

**Comment by ahsan-a** [comment]
netsh, Frick autocorrect and pls read the original error message

**Comment by ahsan-a** [comment]
closed. run ```netsh http add urlacl url=http://+:[port]/ user="Everyone"``` where [port] is your selected port.
